<!-- document.write('')-->
<!-- generated on Jan 3, 2020 at 22:30 pm -->

document.write('<tr><td><img class="publication_img" src="img/teaser/iv2005_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-file-text" aria-hidden="true"></i> A New Pixel-Oriented Visualization Technique Through Color Image</div>')
document.write('    <div class="authors">F. Blanchard, L. Lucas and M. Herbin</div>')
document.write('    <div class="venue">Palgrave Macmillan, Information Visualization, 4(4):257-265, 2005. DOI:10.1057/palgrave.ivs.9500104</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Formation of nucleolar caps during actinomycin D treatment: a quantitative (3D + time) and ultrastructural study</div>')
document.write('    <div class="authors">C. Sauvage, E. Elias, P. Tchelidze, A. Benassarou, E. Bittar, L. Lucas, H. Kaplan, D. Ploton and M-F. O\'Donohue</div>')
document.write('    <div class="venue">19th Wilhelm Bernhard Workshop on the Cell Nucleus. Münsterschwarzach Abbey, Germany, September 2005.</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> A Preliminary Approach of 3D Simulation of Soil Surface Degradation by Rainfall</div>')
document.write('    <div class="authors">G. Valette, M. Herbin, L. Lucas and J. Léonard</div>')
document.write('    <div class="venue">Eurographics Workshop on Natural Phenomena (EGWNP), Dublin, Ireland, p 41-50, August 2005. DOI:10.5555/2381356.2381363</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> MC Slicing for Volume Rendering Applications</div>')
document.write('    <div class="authors">A. Benassarou, E. Bittar, N. John and L. Lucas</div>')
document.write('    <div class="venue">Computer graphics and geometric modeling (CGGM 05), LNCS 3515, Atlanta, GA, USA, p 314-321, May 2005. DOI:10.1007/11428848_39</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

<!-- document.write('')-->