<!-- document.write('')-->
<!-- generated on Jan 12, 2020 at 11:30 pm -->

document.write('<tr><td><img class="publication_img" src="img/teaser/c&g2006_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-book" aria-hidden="true"></i> SoDA Project: a Simulation of Soil Surface Degradation by Rainfall</div>')
document.write('    <div class="authors">G. Valette, S. Prévost, L. Lucas and J. Léonard</div>')
document.write('    <div class="venue">Elsevier, Computers & Graphics, 30(4):494-506, 2006. DOI:10.1016/j.cag.2006.03.016</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Modeling and Visualization of Cracks in a Desiccating Soil</div>')
document.write('    <div class="authors">G. Valette, S. Prévost and L. Lucas</div>')
document.write('    <div class="venue">11th International Fall Workshop Vision, Modeling, and Visualization (VMV 06), Aachen, Germany, p 177-184, November 2006.</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> A Generalized Cracks Simulation on 3D-Meshes</div>')
document.write('    <div class="authors">G. Valette, S. Prévost and L. Lucas</div>')
document.write('    <div class="venue">Eurographics Workshop on Natural Phenomena (EGWNP), Eurographics, Vienna, Austria, p 7-14, September 2006. DOI:10.2312/NPH/NPH06/007-014</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Hierarchical Tracking of Intra-Cell Structures in 4D Images</div>')
document.write('    <div class="authors">A. Benassarou, E. Bittar, D. Ploton and L. Lucas</div>')
document.write('    <div class="venue">3rd International Conference on BioMedical Visualization, London, GB, July 2006. DOI:10.1109/MEDIVIS.2006.13</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Simulation of Rain Splash Using a Genetic Fuzzy System</div>')
document.write('    <div class="authors">G. Valette, S. Prévost, L. Lucas and J. Léonard</div>')
document.write('    <div class="venue">Information Processing and Managment of Uncertainty in Knowledge-Based Systems (IPMU), Paris, France, p 150-157, July 2006.</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

<!-- document.write('')-->