<!-- document.write('')-->
<!-- generated on Jan 3, 2020 at 20:00 pm -->

document.write('<tr><td><img class="publication_img" src="img/teaser/vis2019_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Interactive Visualization and On-Demand Processing of Large Volume Data: A Fully GPU-Based Out-Of-Core Approach</div>')
document.write('    <div class="authors">J. Sarton, N. Courilleau, Y. Remion and L. Lucas</div>')
document.write('    <div class="venue">IEEE VIS 2019, Vancouver, BC, Canada, October 2019, Invited paper.</div>')
document.write('    <div class="links">')
document.write('      <a href="https://hal.univ-reims.fr/hal-01705431v2/document" target="_blank"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf</a>')
document.write('      &nbsp;')
document.write('      <a href="https://vimeo.com/364569226" target="_blank"><i class="fa fa-youtube-play" aria-hidden="true"></i> video</a>')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/ismm2019_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Hierarchical approach for neonate cerebellum segmentation from MRI: An experimental study</div>')
document.write('    <div class="authors">P. Cettour-Janet, G. Valette, L. Lucas, H. Meunier, G. Loron, N. Bednarek, F. Rousseau and N. Passat</div>')
document.write('    <div class="venue">International Symposium on Mathematical Morphology (ISMM), LNCS 11564, Saarbrücken, Germany, p 483-495, July 2019. DOI:10.1007/978-3-030-20867-7_37</div>')
document.write('    <div class="links">')
document.write('      <a href="https://hal.univ-reims.fr/hal-01982960/document" target="_blank"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf</a>')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/isc2019_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Distributed out-of-core approach for in-situ volume rendering of massive dataset</div>')
document.write('    <div class="authors">J. Sarton, Y. Remion and L. Lucas</div>')
document.write('    <div class="venue">International Conference on High Performance Computing (ISC Workshops), LNCS 11887, Frankfurt, Germany, p 623-633, June 2019. 10.1007/978-3-030-34356-9_47</div>')
document.write('    <div class="links">')
document.write('      <a href="https://hal.univ-reims.fr/hal-01982960/document" target="_blank"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf</a>')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/isbi2019_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Simulating Depth Perception in Virtual Microscopy</div>')
document.write('    <div class="authors">N. Courilleau, Y. Remion and L. Lucas</div>')
document.write('    <div class="venue">16th International Symposium on Biomedical Imaging (ISBI), IEEE, Venice, Italy, p 497-501, April 2019. DOI:10.1109/ISBI.2019.8759160</div>')
document.write('    <div class="links">')
document.write('      <a href="https://hal.univ-reims.fr/hal-01982960/document" target="_blank"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf</a>')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

<!-- document.write('')-->
