<!-- document.write('')-->
<!-- generated on Jan 12, 2020 at 11:00 am -->

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Autostereoscopic visualization of 3D time-varying complex objects in volumetric image sequences</div>')
document.write('    <div class="authors">A. Benassarou, G. Valette, D. Debons, Y. Remion and L. Lucas</div>')
document.write('    <div class="venue">Three-Dimensional and Multidimensional Microscopy: Image Acquisition and Processing XVIII (BiOS 2011), SPIE 7904, San Francisco, CA, USA, p 156-164, January 2011. DOI:10.1117/12.875364</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Multiview image compression based on LDV scheme</div>')
document.write('    <div class="authors">B. Battin, C. Niquin, P. Vautrot and L. Lucas</div>')
document.write('    <div class="venue">Electronic Imaging: Stereoscopic Displays and Application XXII (SDA XXII), SPIE 7863, San Francisco, CA, USA, p 147-158, January 2011. DOI:10.1117/12.872430</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('      <a href="https://www.youtube.com/watch?v=2WgjtlmTBso" target="_blank"><i class="fa fa-youtube-play" aria-hidden="true"></i> video</a>')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Instrument for 3D characterization of autostereoscopic displays</div>')
document.write('    <div class="authors">J. Prévoteau, S. Chalençon-Piotin, D. Debons, L. Lucas and Y. Remion</div>')
document.write('    <div class="venue">Electronic Imaging: 3D Imaging Metrology (3DIM), SPIE 7864, San Francisco, CA, USA, p 64-70, January 2011. DOI:10.1117/12.872120</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

<!-- document.write('')-->