<!-- document.write('')-->
<!-- generated on Jan 3, 2020 at 21:30 pm -->

document.write('<tr><td><img class="publication_img" src="img/teaser/3Dcve2018_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Multi-user predictive rendering on remote multi-GPU clusters</div>')
document.write('    <div class="authors">J. Randrianandrasana, A. Chanonier, H. Deleau, T. Muller, P. Porral, P. Krajecki and L. Lucas')
document.write('    <div class="venue">4th VR International Workshop on Collaborative Virtual Environments (3DCVE), IEEE, Reutlingen, Germany, p 1-4, March 2018. DOI:10.1109/3DCVE.2018.8637114</div>')
document.write('    <div class="links">')
document.write('      <a href="https://hal.univ-reims.fr/hal-01982960/document" target="_blank"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf</a>')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/mam2018_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Iso photographic rendering</div>')
document.write('    <div class="authors">P. Porral, L. Lucas, T. Muller and J. Randrianandrasana</div>')
document.write('    <div class="venue">Workshop on Material Appearance Modeling (MAM), Eurographics, Karlsruhe, Germany, p 11-14, July 2018. DOI:10.2312/mam.20181192</div>')
document.write('    <div class="links">')
document.write('      <a href="https://hal.univ-reims.fr/hal-01982960/document" target="_blank"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf</a>')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/gtc1-2018_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> A Fully GPU-Based Out-Of-Core Approach to Handle Large Volume Data</div>')
document.write('    <div class="authors">J. Sarton, N. Courilleau, Y. Remion and L. Lucas</div>')
document.write('    <div class="venue">GPU Technology Conference Europe (GTC), Munich, Germany, March 2018.</div>')
document.write('    <div class="links">')
document.write('      <a href="https://hal.univ-reims.fr/hal-01982960/document" target="_blank"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf</a>')
document.write('      &nbsp;')
document.write('      <a href="https://blogs.nvidia.com/blog/2018/10/11/gtc-europe-science-research/" target="_blank"><i class="fa fa-trophy" aria-hidden="true"></i> Among the 5 major innovations in Europe</a>')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/gtc2-2018_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Multi-User Predictive Rendering on Remote Multi-GPU Clusters</div>')
document.write('    <div class="authors">J. Randrianandrasana, A. Chanonier, H. Deleau, T. Muller, P. Porral, M. Krajecki and L. Lucas</div>')
document.write('    <div class="venue">GPU Technology Conference Europe (GTC), Munich, Germany, March 2018.</div>')
document.write('    <div class="links">')
document.write('      <a href="https://hal.univ-reims.fr/hal-01982960/document" target="_blank"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf</a>')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

<!-- document.write('')-->