<!-- document.write('')-->
<!-- generated on Jan 11, 2020 at 11:00 pm -->

document.write('<tr><td><img class="publication_img" src="img/teaser/ems2012_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-book" aria-hidden="true"></i> A Virtual Discrete Rainfall Simulator</div>')
document.write('    <div class="authors">G. Valette, S. Prévost, J. Léonard and L. Lucas</div>')
document.write('    <div class="venue">Environmental Modelling & Software, Elsevier, 29(1):51-60, 2012. DOI:10.1016/j.envsoft.2011.10.003</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> 3D displays and tracking devices for your browser: a plugin-free approach relying on web standards</div>')
document.write('    <div class="authors">O. Nocent, S. Chalençon-Piotin, A. Benassarou, M. Jaisson and L. Lucas</div>')
document.write('    <div class="venue">International Conference on 3D Imaging (IC3D 2012), IEEE, Liège, Belgium, p 1-8, December 2012. DOI:10.1109/IC3D.2012.6615141</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Toward an immersion platform for the World Wide Web using 3D displays and tracking devices</div>')
document.write('    <div class="authors">O. Nocent, S. Chalençon-Piotin, A. Benassarou, M. Jaisson and L. Lucas</div>')
document.write('    <div class="venue">17th International Conference on 3D Web Technology (Web3D 2012), ACM Press, Los Angeles, California, USA, p 69-72, August 2012. DOI:10.1145/2338714.2338724</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> High-dynamic range video acquisition with a multiview camera</div>')
document.write('    <div class="authors">J. Bonnard, C. Loscos, G. Valette, J.-M. Nourrit and L. Lucas</div>')
document.write('    <div class="venue">Optics, Photonics, and Digital Technologies for Multimedia Applications II, SPIE 8436, Brussel, Belgium, p 81-91, April 2012. DOI:10.1117/12.922789</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

<!-- document.write('')-->