<!-- document.write('')-->
<!-- generated on Jan 3, 2020 at 22:30 pm -->

document.write('<tr><td><img class="publication_img" src="img/teaser/tvc2015_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-file-text" aria-hidden="true"></i> Robust motion flow for mesh tracking of freely moving actors</div>')
document.write('    <div class="authors">L. Blache, C. Loscos and L. Lucas</div>')
document.write('    <div class="venue">The Visual Computer, Springer, p 1-12, 2015. DOI:10.1007/s00371-015-1191-y</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/DRRW-book-2015_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-book" aria-hidden="true"></i> Stereo and Multi-View Video</div>')
document.write('    <div class="authors">L. Lucas, C. Loscos, P. Bekaert et A. Hilton</div>')
document.write('    <div class="venue">Digital Representations of the Real World: How to Capture, Model, and Render Visual Reality, Marcus A. Magnor, Oliver Grau, Olga Sorkine-Hornung, Christian Theobalt, A K Peters/CRC Press, p 23-37, 2015. ISBN 9781482243819</div>')
document.write('    <div class="links">')
document.write('      <a href="https://www.crcpress.com/Digital-Representations-of-the-Real-World-How-to-Capture-Model-and-Render/Magnor-Grau-Sorkine-Hornung-Theobalt/p/book/9781482243819" target="_blank"> <i class="fa fa-link" aria-hidden="true"></i> web</a>')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/isvc2015_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Time-varying surface reconstruction of an actor\'s performance</div>')
document.write('    <div class="authors">L. Blache, M. Desbrun, C. Loscos and L. Lucas</div>')
document.write('    <div class="venue">11th International Symposium on Visual Computing (ISVC), LNCS 9474, p 92-101, Las Vegas, Nevada, USA, December 2015. DOI:10.1007/978-3-319-27857-5_9</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/ic3D2015_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> A Premixed Autostereoscopic OptiX-based Volume Rendering</div>')
document.write('    <div class="authors">B. Battin, G. Valette, J. Lehuraux, Y. Remion and L. Lucas</div>')
document.write('    <div class="venue">International Conference on 3D Imaging (IC3D), IEEE, Liège, Belgium, p 1-5, December 2015. DOI:10.1109/IC3D.2015.7391834</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf (<i class="fa fa-trophy" aria-hidden="true"></i> Co-Best Paper)')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Indexed Dataflow Network: A Multi-layer and Programmable Architecture to Integrate Both Visualization Pipelines and Scene Graphs</div>')
document.write('    <div class="authors">R. Guillemot, S. Prévost and L. Lucas</div>')
document.write('    <div class="venue">19th International Conference on Information Visualisation (iV), p 35-39, IEEE, Barcelona, Spain, July 2015. DOI:10.1109/iV.2015.18</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/eg2015-tutorial_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> 3D Video: from Capture to Interactive Display</div>')
document.write('    <div class="authors">C. Loscos, Y. Remion, L. Lucas, R. Guillemot and B. Battin</div>')
document.write('    <div class="venue">Eurographics tutorials 2015, Eurographics, Zurich, Switzerland, May 2015. DOI:10.2312/egt.20151043</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/eg2015-short_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> 4D Mesh Reconstruction from Time-Varying Voxelized Geometry through ARAP Tracking</div>')
document.write('    <div class="authors">L. Blache, M. Desbrun, C. Loscos and L. Lucas</div>')
document.write('    <div class="venue">Eurographics (EG), Short Papers, p 9-12, Eurographics, Zurich, Switzerland, May 2015. DOI:10.2312/egsh.20151002</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

<!-- document.write('')-->