<!-- document.write('')-->
<!-- generated on Jan 12, 2020 at 5:00 pm -->

document.write('<tr><td><img class="publication_img" src="img/teaser/jase2010_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-book" aria-hidden="true"></i> Shape-Adaptive DCT for Color Object-Based Coding</div>')
document.write('    <div class="authors">D. Samai, N. Doghmane, M. Bedda and L. Lucas</div>')
document.write('    <div class="venue">Journal of Automation & Systems Engineering, 4(3):182-195, 2010.</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')
        
document.write('<tr><td><img class="publication_img" src="img/teaser/ijdmb2010_teaser.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-book" aria-hidden="true"></i> Multi-view shooting geometry for multiscopic rendering with controlled distortion</div>')
document.write('    <div class="authors">J. Prévoteau, S. Chalençon-Piotin, D. Debons, L. Lucas and Y. Remion</div>')
document.write('    <div class="venue">Hindawi, International Journal of Digital Multimedia Broadcasting (IJDMB), special issue Advances in 3DTV: Theory and Practice, 2010(975674):1-11, 2010. DOI:10.1155/2010/975674</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> A new near-lossless scheme for multi-view image compression</div>')
document.write('    <div class="authors">B. Battin, P. Vautrot, D. Debons and L. Lucas</div>')
document.write('    <div class="venue">Electronic Imaging: Stereoscopic Displays and Application XXI (SDA XXI). SPIE 7524, San Francisco, CA, USA, p 572-582, January 2010. DOI:10.1117/12.838908</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

document.write('<tr><td><img class="publication_img" src="img/teaser/no-image-available.png"><p></p></td>')
document.write('  <td class="publication_data">')
document.write('    <div class="title"><i class="fa fa-users" aria-hidden="true"></i> Real 3D video capturing for multiscopic rendering with controlled distortion</div>')
document.write('    <div class="authors">J. Prévoteau, S. Chalençon-Piotin, D. Debons, L. Lucas and Y. Remion</div>')
document.write('    <div class="venue">Electronic Imaging: Stereoscopic Displays and Application XXI (SDA XXI). SPIE 7524, San Francisco, CA, USA, p 323-333, January 2011. DOI:10.1117/12.838829</div>')
document.write('    <div class="links">')
document.write('      <i class="fa fa-file-pdf-o" aria-hidden="true"></i> pdf')
document.write('      &nbsp;')
document.write('    </div>')
document.write('  </td>')
document.write('</tr>')

<!-- document.write('')-->